image: registry.gitlab.com/web3labs/internal/k8s-deploy-helper:latest

variables:
  DOCKER_HOST: tcp://localhost:2375
  KUBE_DOMAIN: epirus.io
  API_AUTHORITY: https://auth.epirus.io/auth/realms/EpirusPortal/
  PORT: '3000'
  API_URL: https://$CI_JOB_NAME.api.$KUBE_DOMAIN
  KDH_SKIP_KUBEVAL: 'true'
  KUBE_NAMESPACE: web
  NEW_RELIC_LICENSE_KEY: eu01xx6d8c67cda2750aeb6c64f847b76640NRAL
  NEWRELIC_APP_ID: $CI_JOB_NAME.epirus.io
  KUBE_URL: https://explorer-2-explorer-b1f753-c641d12d.hcp.westeurope.azmk8s.io:443
  KUBE_TOKEN: 7f2ecd5f635cda3a5b5b1953472370eafefe151d51b377409face8cf2f2c22219ff1da303f8598ec4887a04c7f8d383cc04676158019463f046969845cadcbcd
  KUBE_CA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV5RENDQXJDZ0F3SUJBZ0lSQU1QdzRUZUF0SE9NaHNLUEprNTh3V293RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTVRreE1qRTJNRGsxTlRFMVdoY05ORGt4TWpBNE1UQXdOVEUxV2pBTgpNUXN3Q1FZRFZRUURFd0pqWVRDQ0FpSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnSVBBRENDQWdvQ2dnSUJBTmF3CkJiQXF3OXArTlBzeDB3R1hZSzdNWVhBVEd5aStidElGdStCaHdaNlY1dUl5MHdXOTUwREJaaHl4YXZ5enc3eE0Ka3VKOTZyQ0JSeWVrakFDNUpZVzJrL0RrOHdaeXdPWFRPMTNIc1cwcTV5MVhhRHJta1lleUhDdWdZWWE4Z0MrZQp5WG5nK3ZTNVFBdWRXWDlNZjNHWjlrZHo0NmJPV0ZrUHhxQmJaaXJDWERBRENTNU9nQ1NGRjBMeUUwVVJnZ2l6Cklzcjc3dENqY2E2VGhhRVFQVlcyZi8rdW5URDBQSUkxVW5ENE5Lek1jQTE3dW0xajgreWlrNWNFcU5vdEFYMCsKS2FvWnhZem1qQU1HdmlWeGNrR0VMbDBSbWN6WW5SSGpaOGFLYjBqWjdiK2xlLy9BQTJoSFY2Mm9kY2hJUUFvUgp3d2U3clA0VWNaZUlRd2t5Y1ZYWmpwY0VMVVpoTDNZVFduNm9WMDNCUm1ibEhuZm4xN0FUWFJxcUpsL293NUp3CjB4a0Q3NUMrdi9ldnhQWEhpN3VNcm1XZExEZ2I4ZmlCWWJMZ2pDYkszbGtESXhuUTByRHNlaU0zdldQa0YzWkMKVDMyNkozQzZuUzlBNWF4dURhMStxSmd4YWc4RFY3OE5iMkJKbm50R0w1THRPbDFNZndtOU4vZFc3ZitRK0VtMwp4bFFqTEtlLzM1d3lDU2hSS3lhWnQ2dWtidWQ5WWpFRXMyYi9VelNZQ0JRVlYvTHQ3YXgvNWcxNHMza2Fldmk4CmgzZVpySFlERkFZMUhuNzBZTVVEYmluNFBHTUo0cHpWOFhIQ3MyQ21MNUZKaUJFaGtWSVFFWkJDMmUxQ05Yc0oKa2k3b3FQZ1JGKzBIa1JOSVJSVTFiYjJLTGk5SVcxVXFtLzNWVGMwN0FnTUJBQUdqSXpBaE1BNEdBMVVkRHdFQgovd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQm9Sa2NSCkxxSnFlOUQ3SVF5RmJzaGtNODBFcHIzRUQ5VEdjZFBPZ2RHamsrY01PdXA4c3p3L0IzTkVPQ2s5aU9ubVdLVnkKTFVjTzJkUEpJaHBKSmM2aVUyQUlOaTZteitCZW9oNk4wWUxZSFZLVjQ4YmkvNmdQT29XR29xeWNJY3ZuZC8xcwowd2JLa3NlRmh2WmQrcy9RWE9lU3RTSjRkaW1QWTN5S2V4RDFNWkZwbnM5MW1YeVovRWZPK2VkNndZT3FYak9HClBaakZHS2V3K0tXWUNkYlAvOFdCckl1NWh4MGZwSjlCZ2FvWlJzclI0b2JyQlBLQnprTHM4WjMvMSs3U3pvaVoKZ0NiNWFJTnltVHNFUmJhdmxpZDJ6UytvRXcxN093YmtrakZtUno1dlBkNjdOZmRGOXlzQmQ3UFM4blRMbHRiVgoybXV1MlhIYkZFUEowdHFtdTA0aDB0Z3RnWURQbXArZFV1TC80dHJObEc2VUkwbnkwN1p3ZjhHQi8yRWZGQ0dzCjBxTGI2TDFrSkZJajcxOVQxWkR3MmRXdDRBSTQ0RWZJMDV2N0F6WU1FTFkvdW5kZjJFSWJGcjEwdWNsY1FhbU4KTFlQeWw2a29ORWJBc1lteExnNDQ2S3NkOXB2MlZza3I5ZGJ5bE8zS2E3NFV2NTZPUGF3Z1pwejFveTZQYmtLVgpXTW9iZERaS2ovSit0WjZJbWVMbTBHaUJaanM1Mi85NTZJQWR2UUt0WTRRYi9UcW9QcndlVEgxVlllR3NyQ0Z2ClJ3dy92R2VNUEpxWW9xaHZXdWdURUZ0UDhDVitXRERzakQxT3hxOXFWRC9JNGFMY2FMRnR3UEF2dnRtRkt3anoKVnQ5eTNDeVNKLy9RTzFjN1FFcG9QaEh3VTljNHNHZWRUbTBWVXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  KUBE_CLIENT_CERT: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUUvVENDQXVXZ0F3SUJBZ0lSQUlta2dMZ2E2THl3RFF4M0ZKNU9lVWt3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTVRreE1qRTJNRGsxTlRFMVdoY05NakV4TWpFMU1UQXdOVEUxV2pBdwpNUmN3RlFZRFZRUUtFdzV6ZVhOMFpXMDZiV0Z6ZEdWeWN6RVZNQk1HQTFVRUF4TU1iV0Z6ZEdWeVkyeHBaVzUwCk1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBeEhpcFpDUCtseTlLK2JpWUx3YTgKTlFkb0N0R1RpSDVYNEpyMHhBSHpLS3dIY3drQTVXTzd6emV1Yzh1V1d0dEFkdHJFZDQ0M3pqWGJBU3p1V1JVdAorUHNtUTYyaEJmaWVsb0k2ZUwrSWVFc2JhcUcvcjUvQnpnbGROcUE0OGR1c2ZIbmRUMUJPMUtlLzJVOUZ5NXhPCnpXckdTUUowaVNZMHdxT1hwTXZidzROaXVUNnlxd0tNc25TSEk5eXkxZXJFRzk4TkdlV1o3WkF1Z3czeEFuQkoKNjVUb1piNFBTZ0hvbXp3UXkySTJ1aytKQ05aSDhzQzA4UUZFK2RtVWxLU0FDbElEeEpnblJvV3UzV1lsam52RQpZUGhGaVJrMXExTEpYelgyWWRTMHN0K2RZOTdQa3MvMTVhTDljb3ZDa1JLdFRibkM5WW1XY0wrb0pLaUhpZFJuCm1KemRqTkU5MHh6M3pnVkViaFBQZ1JLcEMyaXY3UHZ5cWhXUEl6TExXbUhUR2R4K2hPTnpRd25SSWUxNU1PVlkKWEpEcDI2WFdGeW5VMm5OdmFTSStCUC9lWFlVNEpLQ1JVaVR3WWVHWVJ6Ui9xL3RHZS9jdDJJVkY5SXp3eWpxTwpwRExJYk9acVYxMFp6RHFhRHpNUU1aMVNIY25FOTV4M0VYYytYMXE3bDdieVNDYjRQVEM2UGRTaTFEai9tSjhxCmVqMmdtKzRQL3g1U3VJZWpPMm9WWFRYMTg4MFA4YjZLemVNN1ZIU25rc203bjZVNXBCeHkxemlGUk9CM1lqSjUKbkF4eVAwVGNrbFR6Q0YyQ2NycVBDUGFKZnpZaHVBNWkxQmZLa05UaGdWYStVTFR3SU9vQWp1WXh0bHhrcUc2TQp4OE5Ga3hDdVloTEs1WEdZbStZM25QRUNBd0VBQWFNMU1ETXdEZ1lEVlIwUEFRSC9CQVFEQWdXZ01CTUdBMVVkCkpRUU1NQW9HQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUIKQUFzT2QxWjh2RFZ0RVp1ME9Bbml6Vjk4dUFmd00ybU40SkVmZkREeks3akl4M0luMXIwZTBZdGZEdTF5NUg5aApPU3EzL2lnMDdQaWY5YTJYejhnMEFqWnZMRWVVVzZaaFFwb1BqaXlaa0d5SlBXdkxUSTNsRkZvTFdYQldmQUpiCjJ4OXowQmg2RTdyOFBsWXkzTnZHVy84WFpXY2lLK1JVY1NEQ0FiRXhQZVEya0hHeUVKVks0dUYrQ245cUR6WnoKcVJFdURGV2JXUGxKbmg0ZS9RR0VXZ3IwSnJ1ektoNGFJQjd4b2E5M29LZFVyK3lSOERXK0xIc2ovWkJvWkhDagpmVDV2ckhYV0crTHgxSk1RMVEwMWdkaTBTTjRWT3FyTHFac0tLaWZpd0ZKMmxmakxjUitXYlYyK2cxWXZ1QThsCnlsZnZ0bTlVNEVjUjJTWWdPOHU0cDNmTExlVjErMGJRakVyUU14WFdob1lNTXZYQTRaeU45TndvV2hQZ1V4MVEKdzQ1RkYwbGNjSS9xcmhKS2F1Z2VGMzljZ2hCbHVlNFUxaHkvSmI3dWFjU0JxVEZwR2Z5UXRlSndDZld5ZlE2eAprZ3hMekw2NzJKWnUxT2lGM0k1cDc1QmVjSHVKckdXZERBQVZ1bDF4QnYyVWZYVnB3TzRJMVJDWU1Ib01Fc2tiCmhqSmlDSXZTTXNxYUNJa29HYTErcVNqTTJFVmJDOUZydnM0bi9PaDZTVWd6cVF0WlVkeFdpY2ZvZ3pRVWRBTmEKb0lWYVJUK3UvWFExdWhlc253MVVPcHVrcWlsUzAxQ3Q2MWJNRWM4L3oxNmVFUG1razZsa040TUtVRkRYdXdwSApKQk1xU0FMNGUxcnVGcVZHMlpINGp0NUtpV212b3Q1S01BUFh3cnRDdHZPTwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  KUBE_CLIENT_KEY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS1FJQkFBS0NBZ0VBeEhpcFpDUCtseTlLK2JpWUx3YThOUWRvQ3RHVGlINVg0SnIweEFIektLd0hjd2tBCjVXTzd6emV1Yzh1V1d0dEFkdHJFZDQ0M3pqWGJBU3p1V1JVdCtQc21RNjJoQmZpZWxvSTZlTCtJZUVzYmFxRy8KcjUvQnpnbGROcUE0OGR1c2ZIbmRUMUJPMUtlLzJVOUZ5NXhPeldyR1NRSjBpU1kwd3FPWHBNdmJ3NE5pdVQ2eQpxd0tNc25TSEk5eXkxZXJFRzk4TkdlV1o3WkF1Z3czeEFuQko2NVRvWmI0UFNnSG9tendReTJJMnVrK0pDTlpICjhzQzA4UUZFK2RtVWxLU0FDbElEeEpnblJvV3UzV1lsam52RVlQaEZpUmsxcTFMSlh6WDJZZFMwc3QrZFk5N1AKa3MvMTVhTDljb3ZDa1JLdFRibkM5WW1XY0wrb0pLaUhpZFJubUp6ZGpORTkweHozemdWRWJoUFBnUktwQzJpdgo3UHZ5cWhXUEl6TExXbUhUR2R4K2hPTnpRd25SSWUxNU1PVllYSkRwMjZYV0Z5blUybk52YVNJK0JQL2VYWVU0CkpLQ1JVaVR3WWVHWVJ6Ui9xL3RHZS9jdDJJVkY5SXp3eWpxT3BETEliT1pxVjEwWnpEcWFEek1RTVoxU0hjbkUKOTV4M0VYYytYMXE3bDdieVNDYjRQVEM2UGRTaTFEai9tSjhxZWoyZ20rNFAveDVTdUllak8yb1ZYVFgxODgwUAo4YjZLemVNN1ZIU25rc203bjZVNXBCeHkxemlGUk9CM1lqSjVuQXh5UDBUY2tsVHpDRjJDY3JxUENQYUpmelloCnVBNWkxQmZLa05UaGdWYStVTFR3SU9vQWp1WXh0bHhrcUc2TXg4TkZreEN1WWhMSzVYR1ltK1kzblBFQ0F3RUEKQVFLQ0FnQXRqTFBvN1pkbXdhWW1ReSsxSjJDWEFzS1NUNGhleXJ2ZzdNdjJiV1ZNZHFXN2U4ampaYjN6Q3J1OQpTT1B3NklnSGhpeXFjeVJwQUg5bnhGejE5ajBVVGxYT3R3QnYrL1g0ZXZUSGJkQmI0ejNWK080UjczM2xJTEtsCnFYdktSdDIwZGlSaThRRjF0L1o0a1RKalJEZlkwL3BvanRNcHdOdldqRXJxQUFGUlVMS2dzL0tFUnpFTFpveTIKT2NLVWFidFJvdUxNc0RpQnBUM0RVSVloeEpxK3JXVTd3VmFXRjk4dnJqdE9pOVNZV1R3eCtrdnY4ZEdCVm9RQgpVUHByZzcvVHBMUU83aCtjNy8xY2d3UU9CbysrMDVCN2VvYkEwNDZ3TGppUzhkZDY2UEQ2YUh2RFU4ZDBsOWNlCnFWeFFlZjRIMlJ0a0JhUUZPOG5seGRTMmxiSDJmWGNOcnpnMi9qL2l2UUhyK28vb1MxMW1jWEJsR0VPYjlUWmQKRjcxZ1ZsM0QvZGlIWjhweUNibVd4M0o3cVFvNzR0bWhhMVZ6TW1ydFJWMU5GVFJSem91a01YV0w3SzluSjZOWAp6Smh0T3dZNmlkdU9JK3FtSjM2OFhYU2FGNzByYkdJSy96TWxOKyt5MDRPVGJCRS9idkhlbzdzSG5hZUV0bUt4ClA5cEtCb25pMFN0cS9kOTk4anV6M1dKWkpabHBSdWthUWJmbVRKSi9IWE9KR01oSzlJSVRHd1RkemtsQ0sxS1kKNVJ0OWVzMU9teUN2M1dtOTZNazdTWk0yd2NBelN6ODdqcXZkVm1mQ1Y1TmRLMkozTlhIWXlaVGx1T1puMGpwZgpqU3U0UzcyUUZnb1U5ZFJpazBJUDk0T2hzU0Z4UEFMbktGd0tzaW52Vm5lS3g4T295UUtDQVFFQXpibU0yejFWCjdsOEtERlcyKzY0WGpRMFVaYkZYbEJXclhvUVd5UlpVY3Q4T29vZFZub25Sc2JMVEd5a3U0OVl0TEd2TkpSekkKL01aVnRuOTloMkdoQ3RkM2hDcVNYZ3JOY0dkT0xOUm4wUHNrWmltVjNkc2VEOU5XSnZoS2IvRGNqVC85ZEhITAoyRk9ZYnNRcnVBZ1diMk83U1o0NUtzM3hvQXJqcDNLdjhzSllzSE1QMExZTVFFWkNiZjlHYmhWWloyaGNGalVLClFyNTJLZFpxTDkvdG9sZkdobkNjZnp0MmhxR0gxZWVteDZ0alhONUZTT1FjUW1SeHNKMDRNK1E4UG1sdm1WTkEKMFdWY3BjOHlDaUdpejJUSWJ4Q05GZ0swS1kvanBpbUtOcG5UK3VJMWJ6d0U2TXZ2Y2hQcEpqbVBpZ3VBYU9RMAoxUEZzcUR2M1VNdFpNd0tDQVFFQTlId3pXRlU4RWhMbkFMU2FwVGxTci9BKzM5VjJzampJZy94ckt5Z1pVRlpkCi9uc09QWUE5ODkva1FLYU8zcG1GbXpFTnBPWjhHNklOTEtLQ2RjMi9xc3oxd1ltZlRBRjd1V0VucC9UTjZMTUsKSUF2UWNMaWc0VVBJRkRSSlExM3Y3RFNqMjRyMElaWkZpTTNya3ZJVGozOUtnOE0yWlVaSWpJRDF2bGhvZ3JibgpvSnE5cmdTWjRNS0F1VVhVZ0RxRWl0VDlsSDNJVmRxZitwNEpNWThLdlh5Tm9lQXYwdHA0ZWdGN25jUVhLMjVDCjhvcVFYQ3lEYytiZExuWlFEbkJiVlJYT0RlQWZnSkhOajZPSmZ6T1FhVDE2VE5uN3FZNEswMFNXVitBa1NoQ0sKaktrMi8wY0NTOFJwcGRDdEkvSkVCdUZsSUN1Mmx0V0JBSUtJRmxlWlN3S0NBUUVBeGxrVzhLNnpjaTlaemNpNgpzdkFJTHV1a2RlUEZiN1p3MHFFQ0l3RVBqTzE0KzhVR0RPUU9OSWtZdHdBL0FGYVltVkthcVNTV3QvZzEzYzRQCjVuNS91YWRDeVVBT2ZQTm5YZStNVlBhNTNhaTJVSFhaMDl5V29HVi9rL1VpTjhsL3JBUTlSNDhNSGRlRGlaQkUKSXB4Um5UWUg5aFBDUkgzcGNBZnZ0SnVEL3NmWW9NOWZPVGk4bVIva25vOVloWHk2QlZSK0xMOFkxSDgwQ0dSOQpYd2xFNFpoRmhZdC9wOEJhSjdZSDlIbnp1R0dMWEpmRkwyRVh5ZjkwQ2ZlYm41UjNiU2xVK3Z4azZ6OFNVNTl3ClBJcHZvZ3dtbjhiU2NKMU12U0hKT0lTbWlMeEp3SU5uUjRjVHFLd3ZnY3FtcVQ4b0lNMjBFZTJzN242UzU2VmgKYnhtUU53S0NBUUVBNk50eXUrdFNyNVE1V0w2cm5EcWd1dG9EeUlVejdFT1JGOFRPL2VmUFZHa3VWVGMzTlBSMApEVmR0dXZYb2xiTjdRWGpUR2dBOHJNVUg3ejlKS3BLd3Z5ay8yUG9QTXdFbXFrWVMwekdpL01PcUhTT2pmL2taCm9mUkJHSjFFT2xtNkxpdGs5YkcvSEU1WUpCaWRDdlJ1RlBxVUtqTkFGKzE5SS9XZ0dZOXkyeTBDS0VHNTc0aUsKVnp4cUJneXdmUUUvUkV2Z3loR1RRZEpkRlFKNGx5ODZkNGV1RGtQTXlQTTBWR0FkTVFLWFh0SkNDV2hZWHJJMgo4YWt0ZVJkTzRMRzdDNnNjK3JKQXp1QVAvWU14Ym1uYVhhSWtYaFl3VUNudHZaTlI3cGlaZDhHUmRLK21walVuCnhxcG9SWG9mcm1FTTBkRFQxSFJPRUJPQ0xzNGtkOE12U1FLQ0FRQjZCWE9aU3lMei9pZXU0bFhiYjJwK1JGNGwKdDY1S0xmY0s1NVk5NXBJNDk5NklKc0VmVE8wemxJQ2tOcWgyTzlvTW5DNFlOR3ZSa1BwQTNwUnZaQVlLbWZJcgpKYVhraVhTYXhoS1R6THVPV1RuMDdJMmhRS0szZWRJRkJLc2M3QW1PUUlveFVPeWVLRjZZcURjWTF4aWN5S0c0CmMwREl6b1BReitKa2pCeFlyK1ZZd05KME53L29VTWpGWkVEVzZOWkZYNVk5Q2Fob3JFNW5QME1iUGNyT3FzRUIKRWNzd3VVQXpFUVhVR2lxZDFXSXU4S1p3di9mQTBwelpKUTR5Wlk4Nk9pbXNSeWZxTno1UnFGT0piekFWbHVWZQo1azlkdjBPeDlpSTlHVko5QXJvVmhra1ZoRjNNN1dINnMzRXNRaEMrTmFwSzlGVkcxOWU5bGxKYklDNFUKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K

services:
  - docker:18-dind

stages:
  - build
  - dockerbuild
  - review
  - staging
  - smoke
  - production
  - taglatest

build:
  image: node:12.14.1
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
    - npm run lint

docker-build:
  stage: dockerbuild
  script:
    - command build
    - echo BUILD FINISHED

test-merge:
  stage: review
  variables:
    API_URL: https://test.api.$KUBE_DOMAIN
  script:
    - command deploy
  environment:
    name: test-www/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
    on_stop: stop-test-merge
  only:
    - branches
  except:
    - master
    - develop

stop-test-merge:
  stage: review
  variables:
    GIT_STRATEGY: none
  script:
    - command destroy
  environment:
    name: test-www/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  only:
    - branches
  except:
    - master
    - develop

test:
  stage: review
  script:
    - command deploy
  environment:
    name: $CI_JOB_NAME-www
    url: https://$CI_JOB_NAME.$KUBE_DOMAIN
  only:
    - master
    - develop

test-smoke:
  stage: smoke
  variables:
    GIT_STRATEGY: none
  allow_failure: false
  script:
    - docker login registry.gitlab.com -u gitlab+deploy-token-71781 -p wg-rqs1dB45jeyqHifqK
    - docker pull registry.gitlab.com/web3labs/epirus/smoke-tests:latest
    - docker run registry.gitlab.com/web3labs/epirus/smoke-tests:latest headless
  only:
    - master

ropsten:
  stage: production
  script:
    - command deploy
  environment:
    name: $CI_JOB_NAME-www
    url: https://$CI_JOB_NAME.$KUBE_DOMAIN
  when: manual
  only:
    - master
    - develop

rinkeby:
  stage: production
  script:
    - command deploy
  environment:
    name: $CI_JOB_NAME-www
    url: https://$CI_JOB_NAME.$KUBE_DOMAIN
  when: manual
  only:
    - master
    - develop

mainnet:
  stage: production
  script:
    - command deploy
  environment:
    name: $CI_JOB_NAME-www
    url: https://$CI_JOB_NAME.$KUBE_DOMAIN
  when: manual
  only:
    - master

demo:
  stage: production
  script:
    - command deploy
  environment:
    name: $CI_JOB_NAME-www
    url: https://$CI_JOB_NAME.$KUBE_DOMAIN
  only:
    - master
  when: manual
  allow_failure: false

eximchain:
  stage: production
  script:
    - command deploy
  environment:
    name: $CI_JOB_NAME-www
    url: https://$CI_JOB_NAME.$KUBE_DOMAIN
  only:
    - master
  when: manual
  allow_failure: false

taglatest:
  stage: taglatest
  variables:
    GIT_STRATEGY: none
  allow_failure: false
  script:
    - command push
  only:
    - master

deploy-free:
  stage: taglatest
  variables:
    GIT_STRATEGY: none
  when: manual
  allow_failure: false
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker pull $CI_REGISTRY_IMAGE:latest
    - docker tag $CI_REGISTRY_IMAGE:latest web3labs/epirus-free-web:latest
    - docker login -u web3labsci -p fZWfZCYsZos2pp6H
    - docker push web3labs/epirus-free-web:latest
  only:
    - master
