export enum ETagType {
  Private = 'Private',
  Self = 'Self',
  In = 'In',
  Out = 'Out',
  Block = 'Block',
  PrivateContractCall = 'Contract Call',
  PrivateContractCreation = 'Contract Creation',
  ContractCall = 'Contract Call',
  ContractCreation = 'Contract Creation',
  Transfer = 'Transfer',
  Custom = 'Custom',
  ERC20 = 'ERC20',
  Fungible = 'Fungible',
  FungibleERC20 = 'Fungible (ERC20)',
  ERC721 = 'ERC721',
  NonFungible = 'Non-Fungible',
  NonFungibleERC721 = 'Non-Fungible (ERC721)',
  ERC1155 = 'ERC1155',
  Hybrid = 'Hybrid',
  HybridERC1155 = 'Hybrid (ERC1155)',
}
